import { QueryProvider } from "@/provider/queryProvider";
import { SnackbarProvider } from "@/provider/snackbarProvider";
import type { Metadata } from "next";
import { Roboto } from "next/font/google";
import "./globals.css";

const roboto = Roboto({
  weight: ["400", "700"],
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={roboto.className}>
        <SnackbarProvider>
          <QueryProvider>{children}</QueryProvider>
        </SnackbarProvider>
      </body>
    </html>
  );
}
